include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  anti-patterns:
    - long-method
    - long-parameter-list

linter:
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    sort_pub_dependencies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_private_typedef_functions: true
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: false
    await_only_futures: true
    flutter_style_todos: true
    prefer_const_declarations: true
    prefer_foreach: true
    sized_box_for_whitespace: true
    sort_unnamed_constructors_first: true
    valid_regexps: true
    void_checks: true
    use_rethrow_when_possible: true
    library_private_types_in_public_api: false
    constant_identifier_names: false
