name: move_app_fileshare
description: AirDrop for all Platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dex_widgets: ^0.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bot_toast: ^4.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dio: ^5.0.0
  shared_preferences: ^2.0.17
  file_picker: ^5.2.5
  dx_http:
    git:
      url: https://github.com/debojyoti452/dxhttp.git
      ref: main
  move_db:
    path: ./move_db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  analyzer: ^5.4.0
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
