name: move_app_fileshare
description: AirDrop for all Platform.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dex_widgets: ^0.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bot_toast: ^4.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  shelf: 1.4.0
  shelf_router: 1.1.3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  analyzer: ^5.4.0
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
