name: move_db
description: MoveDb is a Flutter plugin for accessing the local database.
version: 0.0.1
homepage: https://opensource.appworld.in

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  path_provider: ^2.0.13
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.swing.move_db.move_db
        pluginClass: MoveDbPlugin
      ios:
        pluginClass: MoveDbPlugin
      linux:
        pluginClass: MoveDbPlugin
      macos:
        pluginClass: MoveDbPlugin
      windows:
        pluginClass: MoveDbPluginCApi
